---
title: "practica 9"
format: html
engine: knitr
editor: visual
---

descargo phangorn

## Ejercicio 1

escribo mtdna en la consola y me dice: 42 sequences with 16603 character and 974 different site patterns. The states are a c g t

¿Puedes confirmar el número de secuencias? hay 42 secuencias

¿Qué longitud tiene el alineamiento? Tiene una longitud de 16603

¿Qué función usarías para extraer los nombres de las secuencias? names(mtdna) y me proporciona una lista de los 42 nombres \[1\] "G.gorilla_D38114"\
\[2\] "P.troglodytes_JF727212"\
\[3\] "P.troglodytes_JN191207"\
\[4\] "P.troglodytes_JF727168"\
\[5\] "P.troglodytes_HM068590"\
\[6\] "P.paniscus_KX211934"\
\[7\] "P.paniscus_KX211928"\
\[8\] "P.paniscus_GU189658"\
\[9\] "P.paniscus_GU189664"\
\[10\] "H.heidelbergensis_NC_023100" \[11\] "H.s.denisova_NC_013993"\
\[12\] "H.s.denisova_FR695060"\
\[13\] "H.s.denisova_KX663333"\
\[14\] "H.s.denisova_KT780370"\
\[15\] "H.s.neandertal_KX198085"\
\[16\] "H.s.neandertal_KX198086"\
\[17\] "H.s.neandertal_MG025538"\
\[18\] "H.s.neandertal_NC_011137"\
\[19\] "H.s.neandertal_FM865409"\
\[20\] "H.s.neandertal_FM865407"\
\[21\] "H.s.neandertal_KX198088"\
\[22\] "H.s.neandertal_KX198083"\
\[23\] "H.s.neandertal_MG025540"\
\[24\] "H.s.neandertal_MG025536"\
\[25\] "H.s.neandertal_MG025537"\
\[26\] "H.s.neandertal_KX198087"\
\[27\] "H.s.neandertal_KX198082"\
\[28\] "H.s.neandertal_FM865408"\
\[29\] "H.s.neandertal_KU131206"\
\[30\] "H.s.neandertal_KF982693"\
\[31\] "H.s.neandertal_FM865411"\
\[32\] "H.s.neandertal_KY751400"\
\[33\] "H.s.neandertal_MK033602"\
\[34\] "H.s.modern_EU092846"\
\[35\] "H.s.modern_EU092665"\
\[36\] "H.s.modern_JQ045086"\
\[37\] "H.s.modern_DQ779927"\
\[38\] "H.s.modern_DQ779932"\
\[39\] "H.s.modern_AP008640"\
\[40\] "H.s.modern_AY495317"\
\[41\] "H.s.modern_J01415"\
\[42\] "H.s.modern_FJ236981"

## Ejercicio 2

¿De qué clase son los objetos mt_nj y mt_upgma? puedo usar la funcion class() para saberlo. Son de clase phylo, o sea son arboles evolutivos.

Consulta la estructura de estos objetos (str(mt_nj)).

str(): str(mt_nj) List of 4 \$ edge : int \[1:81, 1:2\] 44 44 54 54 53 53 52 52 51 51 ... \$ edge.length: num \[1:81\] 1.97e-04 2.26e-04 -4.37e-08 4.37e-08 8.51e-08 ... \$ tip.label : chr \[1:42\] "G.gorilla_D38114" "P.troglodytes_JF727212" "P.troglodytes_JN191207" "P.troglodytes_JF727168" ... \$ Nnode : int 40 - attr(*, "class")= chr "phylo" - attr(*, "order")= chr "postorder"

Represéntalos gráficamente (plot(mt_nj)) y consulta la ayuda de la función plot.phylo() para saber qué opciones de representación gráfica tienes.

?plot.phylo para ver la ayuda, algunas opciones son: type, unrooted, edge.color, cex o edge.width

Para qué sirven las funciones add.scale.bar() y axisPhylo()? Con esto puedo medir el arbol, con la primera funcion, me dice a cuantas mutaciones equivale y con la segunda funcion, añade un eje, que permite ver cuando se separó cada especie en la linea de tiempo o distancia.

G.gorilla_D38114 P.troglodytes_JF727212 P.troglodytes_JN191207 0 0 0 P.troglodytes_JF727168 P.troglodytes_HM068590 P.paniscus_KX211934 0 0 0 P.paniscus_KX211928 P.paniscus_GU189658 P.paniscus_GU189664 0 0 0 H.heidelbergensis_NC_023100 H.s.denisova_NC_013993 H.s.denisova_FR695060 -400000 -39000 -50000 H.s.denisova_KX663333 H.s.denisova_KT780370 H.s.neandertal_KX198085 -110000 -110000 -39820 H.s.neandertal_KX198086 H.s.neandertal_MG025538 H.s.neandertal_NC_011137 -40096 -38515 -38310 H.s.neandertal_FM865409 H.s.neandertal_FM865407 H.s.neandertal_KX198088 -39000 -40000 -41210 H.s.neandertal_KX198083 H.s.neandertal_MG025540 H.s.neandertal_MG025536 -42430 -42540 -43230 H.s.neandertal_MG025537 H.s.neandertal_KX198087 H.s.neandertal_KX198082 -43780 -44290 -44770 H.s.neandertal_FM865408 H.s.neandertal_KU131206 H.s.neandertal_KF982693 -49000 -50000 -82752 H.s.neandertal_FM865411 H.s.neandertal_KY751400 H.s.neandertal_MK033602 -65000 -122287 -110450 H.s.modern_EU092846 H.s.modern_EU092665 H.s.modern_JQ045086 0 0 0 H.s.modern_DQ779927 H.s.modern_DQ779932 H.s.modern_AP008640 0 0 0 H.s.modern_AY495317 H.s.modern_J01415 H.s.modern_FJ236981 0 0 0

## Ejercicio 3

plot(mt_nj_rtt) axisPhylo() hago eso para ver el nuevo arbol ¿Se corresponden bien las distancias evolutivas estimadas con las dataciones? No, hay algunas que no terminan en la misma línea.

¿Qué secuencias crees que se ajustan menos a su supuesta edad? hay secuencias que no llegan al presente

¿Qué razones puede haber para que la edad de una secuencia no se corresponda con la cantidad de cambios que ha acumulado? puede ser por diferente tiempo de generación, diferentes tasas de mutación (tasas variables), seleccion natural o algún error.

##Ejercicio 4
